theme: jekyll-theme-chirpy

title: ""
tagline: QA Automation & Testing Strategy
description: Practical notes on test automation, CI/CD, and quality engineering
url: https://elenakulgavaya.github.io
baseurl: ""
lang: en

github:
  username: elenakulgavaya

social:
  name: Elena Kulgavaya
  links:
    - https://github.com/elenakulgavaya
    - https://linkedin.com/in/ekulgavaya

## Site Verification Settings
#webmaster_verifications:
#  google: # fill in your Google verification code
#
## ↑ --------------------------
## The end of `jekyll-seo-tag` settings
#
## Web Analytics Settings
#analytics:
#  google:
#    id: # fill in your Google Analytics ID
#
#
# Page views settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light — Use the light color scheme
#     dark — Use the dark color scheme
#
theme_mode: # [light | dark]


avatar: "/assets/img/avatar.jpeg"

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: "/assets/img/og-image.png"

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  provider: giscus
  giscus:
    repo: elenakulgavaya/elenakulgavaya.github.io
    repo_id: "R_kgDORNWvjA"
    category: "General"
    category_id: "DIC_kwDORNWvjM4C2gZs"
    mapping: pathname

assets:
  self_host:
    enabled:

pwa:
  enabled: true

paginate: 10
